### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by leporter** [words-sdsc/edX#12]
After install on Windows 10, at first launch I get this error. Troubleshooting:

Error response from daemon: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

   at Docker.Backend.DockerDaemonChecker.Check(Func`1 isDaemonProcessStillRunning)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

crash reported:
A8167BAF-21AC-4D42-A015-54DA91463F6B/2017-04-09_12-30-58

**Comment by zonca** [comment]
Haven't tested on win 10 yet, I'll have a laptop Monday!
Is that in the browser or console?

**Comment by leporter** [comment]
No worries, I'm doing a more thorough setup right now.  Hitting some issues but its going okay.  This bug, above, seemed to go away by going into Docker for Windows, Reset, and selecting "Restart Docker". 

Here are my other notes so far (it's doing the big install now):
1.  error (listed above) when docker tried to start on the system for the first time.  Resolved with Docker for Windows->Settings->Reset->Restart Docker.
2.  Couldn't find Docker Quickstart Terminal - but just telling them to run:
'cmd' in the start panel, then do:  mkdir Python4DS
is likely easier.
3.  C drive wasn't shared, need to go into Docker for Windows->Settings->Shared Drives-> Share C drive (apply).
4.  the text to replace with "C/Users/leporter/Python4DS/" in the text is slightly different than in the command string.

None of these are major (maybe the 1st), but learners will get confused. :)

**Comment by leporter** [comment]
Okay, got stuck on the ip address in chrome.  The commands listed didn't work, but the trick was to do:
ipconfig
The find a VirtualBox Host-Only adapter which, for me, was on 192.168.56.1 so I was able to use:
192.168.56.1:8888 to connect to the notebook server

**Comment by leporter** [comment]
If they end up wanting to use any of our notebooks, etc. on Windows.  We may want to tell them how to open a command window in chrome and run git clone.

**Comment by zonca** [comment]
We can ask @altintas, I think she wanted the students to download the
notebooks one by one from edX.

**Comment by zonca** [comment]
@leporter thanks, I updated https://github.com/words-sdsc/edX/blob/master/setup_docker/README.md with my run of Windows 10, my machine supported Hyper-v, so I added your issues for the case with Virtualbox.
