### ISSUE TITLE
create nbgrader exercise notebooks

### ISSUE THREAD

**Issue by zonca** [words-sdsc/edX#30]
* [x] @zonca - `pandas`
* [x] @zonca - text data, 3 notebooks
* [x] @a1singh - `numpy`
* [x] @a1singh - Machine Learning, 3 notebooks, Classification, Clustering, Regression
* [x] @a1singh - `matplotlib` week 5

Create notebooks on separate pull requests and merge them in.

**Comment by zonca** [comment]
@a1singh @leporter should we do 1 notebook per week or 1 notebook per lesson?

**Comment by leporter** [comment]
I think either is okay.  One larger one per week or a shorter one per lesson is totally fine.  But you only need to do the lessons with programming content. For example, you'd want one for numpy (week 3 lesson 2) but not one for WIFIRE (I don't think).  For the machine learning week, you could have a notebook for each of the topics (lesson 2,3,4) or just one summary one.   As writing, I guess I slightly prefer the per lesson exercises, but I think either option is totally okay.

**Comment by zonca** [comment]
@leporter @altintas I completed exercise notebooks for week 8, they are now merged into the repository, we're done with the first pass of exercise notebooks. I'm closing this issue.
