### ISSUE TITLE
html titles issue

### ISSUE THREAD

**Issue by zonca** [words-sdsc/edX#33]
@a1singh it looks like there is a visualization issue if you shrink the horizontal size of the notebook

![screenshot_2017-05-24_10-35-22](https://cloud.githubusercontent.com/assets/383090/26417420/0433e104-406e-11e7-82a5-44291c65b427.png)

**Comment by a1singh** [comment]
@zonca thanks for noticing. I just fixed it. It now adjusts to match the screen size.
