### ISSUE TITLE
create header notebook for exercise notebooks

### ISSUE THREAD

**Issue by zonca** [words-sdsc/edX#34]
@a1singh @leporter 

we can create a header notebook with common cells to be prepended by `nbgrader` to the assigned notebooks:

http://nbgrader.readthedocs.io/en/stable/user_guide/creating_and_grading_assignments.html#assign-a-problem-set-using-nbgrader

should I go ahead and create it from the `numpy` notebook? or you prefer to take care of this?

**Comment by a1singh** [comment]
I am making copies of @leporter comments in numpy and it is working fine for me.

I don't mind switching to this way if it works for all

**Comment by zonca** [comment]
ok, implemented in #35 , move discussion there.
