### ISSUE TITLE
issues with git bash

### ISSUE THREAD

**Issue by zonca** [words-sdsc/edX#38]
I'm collecting the issues with git bash, then I'll add them as a note to the install instructions

* `more` and `man` are not available
* in Jupyter Notebooks, you cannot access git bash with `!`, so for example `!ls` won't work

someone suggested to use the Win 10 compatibility layer for Ubuntu, but I think that is too complicated.

**Comment by k3nunez** [comment]
- **clear** is also not working.  A student wrote "when i type clear it give me this error('nutc': unknown terminal type)"

**Comment by k3nunez** [comment]
- Point out the importance of Unix

**Comment by zonca** [comment]
@k3nunez probably this is a feedback for the lessons, here let's gather everything for the Git Bash installation instructions.

**Comment by michtai** [comment]
- student cannot open Git Bash

**Comment by zonca** [comment]
text to explain limitations of git bash:

## Notice for Windows users about Unix material

Git Bash provides a Bash implementation for Windows, however some commands are not supported, below a list with the recommended alternative:

* man: man is not supported to access the help of a command. Instead of for example "man top", type "top --help" instead.
* more: more is not supported to display the content of a file, use "less" instead.
* clear: clear is not supported to clean up the terminal, this command is just for convenience, no need for an alternative
