### ISSUE TITLE
Review of Soccer data analysis

### ISSUE THREAD

**Issue by zonca** [words-sdsc/edX#9]
@a1singh 

* add details on how to download and extract data from https://www.kaggle.com/hugomathien/soccer
* Cell 5, better do `df.shape` in another cell, is not related to `any row NULL?`
* Maybe you can also take a look at missing data per column with `df.isnull().sum(axis=0)`?
* Cell 9 explain why you are shuffling
* Cell 14, write also feature name?

        for f in potentialFeatures:
             related = df['overall_rating'].corr(df[f])
              print(f + ":", related)

* First plot of correlations, kind of small labels, maybe just take a subset of those?
* At the end, in the clustering example, do you think you can describe in words what kind of groups are being identified?
* I am worried that `parallel_plot` is a bit difficult to explain and could distract from the most important points of the notebook, is there a way to achieve similar result in another way? maybe using `seaborn`?

**Comment by a1singh** [comment]
@zonca : thanks !

does the docker that students will use contain seaborn ?

**Comment by zonca** [comment]
Yes, see all packages here:
https://github.com/jupyter/docker-stacks/blob/master/scipy-notebook/README.md

**Comment by a1singh** [comment]
@zonca : thanks !

updated the notebook based on suggestions.
